### ISSUE TITLE
please provide a java sample how to sign an xml with PCKS1

### ISSUE THREAD

**Issue by ralfhauser** [SwisscomTrustServices/itext7-ais#4]
and in particular, how to retrieve the signing cert 
![image](https://user-images.githubusercontent.com/1681677/218780778-92f51c5e-733a-48a3-a861-db5780cf0599.png)

see also https://issues.apache.org/jira/browse/SANTUARIO-597

**Comment by paulmuntean** [comment]
we work on this, once this Java sample code is available I will let you know.
